### ISSUE TITLE
My car randomly disappears and I am 'spectating' someone else

### ISSUE THREAD

**Issue by N3er0O** [Starystars67/BeamNG-MP#12]
Randomly (usually after about 5-10mins) my screen freezes and my camera is attached to another player's car. It kinda looks like I'm spectating someone else. Here is a video to show what's happening: https://youtu.be/nPoYc0x7RzY

**Comment by daveywaveyHD** [comment]
> 
> 
> Randomly (usually after about 5-10mins) my screen freezes and my camera is attached to another player's car. It kinda looks like I'm spectating someone else. Here is a video to show what's happening: https://youtu.be/nPoYc0x7RzY

Hi, this happens when someone refreshes their vehicle (necessary for other players to be able to see them). This is currently the way the mod handles new players - you need to tab back to your vehicle. 
Thanks, Dave
