### ISSUE TITLE
Add an improved automatic syncing system.

### ISSUE THREAD

**Issue by jacobcargen** [Starystars67/BeamNG-MP#228]
At the moment you will automatically sync with others when you come to a near stop. I have an issue where I slow down for a moment while racing and driving and it loads the vehicles and causes a huge lag spike during the worst times. This can be quite frustrating. 

My solution would be to have a custom setting for the player to chose how long and at what speed they must be under for it to sync.

An alternative would be to make this an value that is not adjustable and just improve the timing and current syncing a little bit, but I thought it might go well to give the player the option.

For example the player must be under 1 mph (in any direction) and must be consistently below that speed for lets say 2 seconds. I thought this could a great addition to providing a much smoother and cleaner game-play.

**Comment by jacobcargen** [comment]
@20dka This was the draft i was kinda working on, since you assigned this to yourself I will stop working on it. Here is the progress I made. I'm not that great at coding or github yet so I might have done something incorrect. I will link the code anyway incase you are interested in how I went about it. Nothing has been tested yet either. 

https://github.com/jacobcargen/BeamMP/commit/00b8bd0e40f3594a27453813c4c55437c003f71f

**Comment by Starystars67** [comment]
@20dka did you make any progress with this?

**Comment by 20dka** [comment]
> @20dka This was the draft i was kinda working on, since you assigned this to yourself I will stop working on it. Here is the progress I made. I'm not that great at coding or github yet so I might have done something incorrect. I will link the code anyway incase you are interested in how I went about it. Nothing has been tested yet either.
> 
> [jacobcargen@00b8bd0](https://github.com/jacobcargen/BeamMP/commit/00b8bd0e40f3594a27453813c4c55437c003f71f)

@jacobcargen 
Hey, thank you for the issue and your proposed solution! You based your work off of the wrong branch (easy mistake to make, we have the wrong one marked on this repo) so I took your commits and put them over the correct base ([link to my branch](/20dka/BeamMP/tree/Add-improved-sync-feature)). I will reenable the settings you put there and open a PR

**Comment by jacobcargen** [comment]
@20dka Yes, I am quite new to github and this repo, I am still learning. Hopefully the code I made is at least slightly helpful. Which branch was I supposed to clone?

Also, I would like to note that I not esactly sure how syncing, vehicle loading, and vehicle editing work. I read through the code a bit and noticed that the vehicle loading seems to be seperate than edited parts. I intentionally wanted edits and vehcile loading to go through at the same time to reduce all lag while driving in the game. Like I said, I don't understand the code that well, so maybe there is a lot that I overlooked.

**Comment by 20dka** [comment]
We use the branch `development`
You didn't overlook anything, we have a single function for applying both types of queues

**Comment by jacobcargen** [comment]
Oh... I thought I was in development branch? Now, with another look, it seems that I wasn't.

Are you still planning on adding a adjustable option in the UI?
Also another question, is there anyway for me to test the code?

**Comment by 20dka** [comment]
yes, i was testing the UI i wrote for it when a yt recording session started 😅
I'll push my changes tonight

**Comment by 20dka** [comment]
> Also another question, is there anyway for me to test the code?

Yes, you can take your modded files and run them unpacked, with the launcher in dev mode so it doesnt override them
