### ISSUE TITLE
[Bug] Server's onPlayerAuth cancellation message doesn't show ingame

### ISSUE THREAD

**Issue by lionkor** [Starystars67/BeamNG-MP#229]
**Have you read our FAQ/Wiki/#before-you-ask ?**
Yes

**Describe the bug**
When a server is full, or a player is banned from a server, joining the server results in some kind of undefined behavior (for example infinite loading).

**To Reproduce**
1. Find a full server or a server where you're banned
2. Join it
3. See no message

**Expected behavior**
A dialog should pop up with the message the server sends when onPlayerAuth is cancelled.

**Comment by snepsnepsnep** [comment]
Looks like the game never receives the kick packet when joining a server. I'll look into it.

**Comment by OfficialLambdax** [comment]
Is it send? If so then it might be a simple issue.
If the socket is closed right after the message was send then it can happen that the receive buffer is already cleaned before the client was able to read the buffer contents. So windows/linux likely received the data but also the disconnect and if the socket got disconnected before the buffer was emptied then that data is gone.

I cant tell how it works on the lower level, but ive seen it multiple times happen while working with tcp. So maybe its the same here.

**Comment by lionkor** [comment]
Yes, that could be, but that can also be detected. Server disconnect, kick, or any kind of failure should be handled gracefully on the mod's side (or launcher side)

**Comment by OfficialLambdax** [comment]
The launcher does detect that the sockets have been closed gracefully, as can be seen in its console, but it might doesnt tell the lua mod during that phase or in a way that the lua mod cant process during connect/auth.

**Comment by Mack29446** [comment]
This issue has been solved by Launcher PR BeamMP/BeamMP-Launcher#49
