### ISSUE TITLE
[Question] What are pink balls

### ISSUE THREAD

**Issue by lionkor** [Starystars67/BeamNG-MP#230]
Have you checked the relevant area on our Forum / Discord / Wiki? **Yes**

Describe your question in as much detail as possible below please:

There are pink balls in game. What do they mean, and how do you get rid of them?

**Comment by 20dka** [comment]
pink is the color used when none of the other characteristics are met meaning:
not in queue, not illegal(modded), not deleted.
in practice this means the spawn failed
the lua console should reveal more information.
