### ISSUE TITLE
[Bug] Radial menu skips onVehicleResetted

### ISSUE THREAD

**Issue by lionkor** [Starystars67/BeamNG-MP#234]
**Have you read our FAQ/Wiki/#before-you-ask ?**
Yes

**Describe the bug**
The radial menu reset skips the onVehicleResetted and thus all MP-related ways to limit resets, etc.

**Comment by lionkor** [comment]
Nuclear has more info and a fix, but didn't have time to report it - ask there for more info

**Comment by ghost** [comment]
Don't have much to add other than to say it is detected by server when someone uses a recovery function, but is not detected client side by onvehicleresetted (ge lua ) or onReset(ve lua). It uses the "trackvehreset" functioj and I'm not entirely sure how it works yet but I'm trying to figure it out.

How does the client side MPlua detect a recovery? I'll be looking myself when I get home if I don't hear from anyone to see if I can find out.

**Comment by snepsnepsnep** [comment]
The client side detects the recovery with onVehicleResetted which then sends a reset packet to the server.

**Comment by ghost** [comment]
> The client side detects the recovery with onVehicleResetted which then sends a reset packet to the server.

When you say client side, do you specifically mean MPvehicleGE?

Because when I use the HOME option on the radial menu that event is not fired for me in ge or ve Lua. All other resets are detected like when you edit you car and it resets it, regular resets, etc

**Comment by ghost** [comment]
Can someone please give me evidence that it does work like this, I will provide evidence later that it i ls NOT true. You say it runs the onvehicleresetted but it does not for me. Regular resetting does run the function.

**Comment by StanleyDudek** [comment]
I looked into this some, and came up with the following assessment, using launcher 2.0.79, beammp 4.5.0, server 3.1.0 :

![image](https://user-images.githubusercontent.com/49531350/194131878-306be0da-bc0f-4be7-9c30-a999070f0b97.png)

Client side, everything seems fairly normal, onVehicleResetted() is called in all situations where it is expected, including the radial menu. HOWEVER, server side an onVehicleReset() never happens under any circumstance.

Hopefully this helps shed some light on the issue.

**Comment by lionkor** [comment]
Server 3.1.0-prerelease did indeed have this issue, I have just fixed it
