### ISSUE TITLE
[Bug] onPlayerAuth not functioning properly 

### ISSUE THREAD

**Issue by ghost** [Starystars67/BeamNG-MP#235]
**Have you read our FAQ/Wiki/#before-you-ask ?**
Yes

**Describe the bug**
onPlayerAuth does not return properly anymore . When using return, it does not show the in game message as it should. It will also sometimes say it closed a client connection, but not actually do anything and still allow the player to join. This is with no errors showing in console(however that is bugged as well)

**To Reproduce**
Not entirely sure what exactly causes this to occur.

**Expected behavior**
Using return "string" should reject player connecting and display the string given as a reason.

**Desktop (please complete the following information):**
 - OS + Version: Windows Server 2019

**Comment by Mack29446** [comment]
This issue has been solved by Launcher PR https://github.com/BeamMP/BeamMP-Launcher/pull/49
