### ISSUE TITLE
[Bug] Leaving player orbs after kicking 

### ISSUE THREAD

**Issue by ghost** [Starystars67/BeamNG-MP#237]
**Have you read our FAQ/Wiki/#before-you-ask ?**
Yes

**Describe the bug**
After kicking a player with modded vehicle (that's not on the server) it will leave their orb behind with nametag

**To Reproduce**
Remove a player with modded vehicle from sever 

**Expected behavior**
Remove all trace of player

**Desktop (please complete the following information):**
 - OS + Version: [Windows Server 2019]

**Comment by WiserTixx** [comment]
This has been fixed.
