### ISSUE TITLE
[Bug]Joining server from singleplayer freeroam

### ISSUE THREAD

**Issue by ghost** [Starystars67/BeamNG-MP#238]
**Have you read our FAQ/Wiki/#before-you-ask ?**
Yes

**Describe the bug**
Joining server from a freeroam instance will load the players and their positions cars etc, but will not change map. You can see the players hovering around where they would be had you loaded the map properly.

**To Reproduce**
Load a singleplayer map, then join a server

**Expected behavior**
Load the new map

**Desktop (please complete the following information):**
 - OS + Version: [Windows Server 2019]

**Comment by Luc45** [comment]
I've faced this issue too when I was on singleplayer and tried to join a server. 

I don't mean to de-reail this issue, but it might be related. There's a similar behavior when you are in a server and join another server.

I've found a [reddit thread](https://www.reddit.com/r/BeamMP/comments/rrd3ha/cant_switch_servers_unless_i_quit_game/) saying that you had to click on "Quit" on the topbar, which I have never noticed before. I wonder if it would be too hard to invoke some kind of `quit` method before joining another server.

**Comment by snepsnepsnep** [comment]
I've been recently working on getting the issues with switching servers and going to freeroam or from freeroam ironed out so a fix for it should be out eventually. Just takes a lot of time and testing to ensure that everything is unloaded and loaded correctly.
