### ISSUE TITLE
[Bug] onExtensionUnloaded() is not called on server exit.

### ISSUE THREAD

**Issue by StanleyDudek** [Starystars67/BeamNG-MP#260]
**Have you read our FAQ/Wiki/#before-you-ask ?**
Yes

**Describe the bug**
`onExtensionUnloaded()` is not called for loaded mods when exiting a server, presumably because they are deleted outright when cleaning up the mods.

**To Reproduce**
1. Join a server with mods that have extensions containing the `onExtensionUnloaded()` function, with something like a `log` or `print` inside so you can check the beamng.log to see if it has been called. 
2. Click on 'Quit'
3. Open beamng.log
4. See that `onExtensionUnloaded()` was never called
5. Also see that because it was not unloaded, extensions prints `extension unavailable: "modName" at location: "modName"`

**Expected behavior**
When exiting a server, any mods that have extensions containing an `onExtensionUnloaded()` function should have that function called, as some mods need to know they've been unloaded.

**Desktop (please complete the following information):**
 - Win11 22H2

**Additional context**
I opened a pull request with a fix @ https://github.com/BeamMP/BeamMP/pull/259

**Comment by snepsnepsnep** [comment]
Did some further looking into this and it looks like mods shouldn't be registered as core extensions in the first place, instead the modscript should contain something like this
`queueExtensionToLoad('extensionName1')`
`queueExtensionToLoad('extensionName2')`
`loadGameModeModules()`

That way the extensions get added to `extraUserRequestedExtensions` and loaded, and can all be unloaded with a single command `unloadGameModules()`, which gets called by `EndActiveGameMode()`, which is called by `returnToMainMenu()`

**Comment by StanleyDudek** [comment]
Thank you so much! I just tested this method of loading via modScript.lua and can confirm it works as you described, and solves this issue. I will close this issue and associated PR.
