### ISSUE TITLE
[Feature Request] Rolling debug buffer

### ISSUE THREAD

**Issue by O1LER** [Starystars67/BeamNG-MP#272]
**Is your feature request related to a problem? Please describe.**
When using the option "Show debug messages in the console" to look for a bug, the beamNG log gets big quickly. When looking for a bug that happens maybe once every 10 hours, the log file gets huge

**Describe the solution you'd like**
Rolling debug buffer, that gets sent to the log file when a certain key combo is pressed. Last then seconds for example get stored on beamMP side, then once the key combo is pressed, get sent to the beamNG console at once. Time may be variable

**Describe alternatives you've considered**
Rolling log file

**Comment by Starystars67** [comment]
Hi @O1LER , can I just ask for clarification, Do you mean you are looking for log rotation?

**Comment by O1LER** [comment]
If i understand this correctly, log rotation would be to exchange an old log file with a new one. So i guess beamNG already has this.

What i meant was just the MP part.

If MP debug is disabled, the situation is like now, some MP info is written into the NG log.

If MP debug is enabled, as normal some MP info is written into the NG log. But additionally, all the debug info is written into a seperate buffer. Only if a keycombo is pressed, the debug buffer contents are written into the beamNG log.

Might help to cut down on log filesize while still catching the necessary info

**Comment by Starystars67** [comment]
Given BeamNG handles the logging of the game and such I think that this is likely not something that BeamMP can handle.

That said if you have any hints / ideas on a method of implementation then please let me know.
For now though I will close this issue.
