### ISSUE TITLE
[Bug] Custom vehicle color not replicating across server and clients.

### ISSUE THREAD

**Issue by ghost** [Starystars67/BeamNG-MP#273]
**Have you read our FAQ/Wiki/#before-you-ask ?**
Yes

**Describe the bug**
Modifying the color of a vehicle does not replicate at all across the server or to any client. It may be missing from the code itself.

**To Reproduce**
1. Load into a level.
2. Press Ctrl + E to open the selection menu.
3. Select a vehicle & set its custom color.
4. Press `SPAWN NEW` or `REPLACE CURRENT`.
5. View the vehicle from another client perspective.

**Expected behavior**
The modified color of the vehicle should synchronize on the server, allowing other users to see the modified color.

**Screenshots**
There are no screenshots provided.

**Desktop (please complete the following information):**
 - Windows

**Comment by snepsnepsnep** [comment]
Hey, we have been unable to replicate the issue, all colors work as expected when spawning or replacing vehicles. What version of the mod are you running? When in the mainmenu at the bottom of the screen it should say.

**Comment by obtusity** [comment]
Now that I reflect on previous actions, it may have something to do with just custom configurations.

I'm on BeamMP v4.6.2

**Comment by ghost** [comment]
It appears that this issue does still persist, though I had closed it with the doubt that it was just on my end. It may vary, but in general, a vehicle spawned with a custom color through the spawn-menu will always appear the same color as the vehicle that the other client is driving, to other clients.

**Comment by shawnjb** [comment]
As a side-note I have installed the latest BeamMP-Launcher.exe and reinstalled the BeamMP application to confirm that this is still an issue.

**Comment by ghost** [comment]
I have installed the latest version of the BeamMP launcher and reinstalled the BeamMP application to confirm that the issue of color modifications not replicating across clients or the server persists.

I am changing the name of the issue to better reflect the problem being addressed.

**Comment by ghost** [comment]
When a new vehicle with a custom color is spawned, it appears that the color typically follows the same color that is set on the client that receives the synchronization request. This means that if a new vehicle is spawned, it will use the same color as the local user's vehicle, but only that user will be able to see the modified color.

**Comment by OfficialLambdax** [comment]
Cannot replicate.

Wrote a script that is also a client of the server and it spawned whatever vehicle it received from other players, so that i can get the other clients perspective. Colors are correctly received by the script, on spawn also correctly transmitted back and correctly applied on my game client. Tested with default colors and custom colors.

https://www.youtube.com/watch?v=N50sbRqSAEs

What i have not tested is if the vehicle edits are affected - because i know that color changes on a already present vehicles work - i see players do that often.

**Comment by O1LER** [comment]
It is an issue, altough i think it does not happen all the time. I cant provide a video or a log, but i will try to get one if i see it happen again in the future.

But i have two screenshots of my car, that i loaded from a custom config i already had, with white paint:
![image](https://user-images.githubusercontent.com/44237025/211424082-0b9a57ef-e5d6-48a7-ab85-21a0614ee688.png)

Another user on the server saw my miramar as green and yellow, the colors my bluebuck taxi had before:
![image](https://user-images.githubusercontent.com/44237025/211424353-6205fa4a-2c04-4965-bd7d-5e4b88492179.png)

Since he saw the miramar and not the bluebuck anymore, the client had received and loaded the car change, but obviously not with the right colors

(Dont mind the crashed state or the small second picture, its all i have for now)

**Comment by lionkor** [comment]
Are you absolutely sure that this is not because the person who doesnt see the right colors has simplified vehicles enabled in the MP options?

**Comment by Olrosse** [comment]
I'm pretty sure simplified cars also syncs the colors, and the Miramar in the pictures also seem to be modded on both screens so it can't be a simplified vehicle, but what it looks like on oilers post is that it somehow spawned the new car with the paint of the old one

**Comment by OfficialLambdax** [comment]
~~Untested idea
Could be a double que issue.
00:00 You spawn car and play around
00:05 You change the colors of your car
00:10 You switch your vehicle to another~~

1. ~~Now another player may only executed the first spawn so far.~~
2. ~~So now they have a Vehicle color edit and a vehicle jbm edit in the que.~~
3. ~~Maybe, the jbm edit is for some reason performed first and then the color edit. And that could possibly explain it.
It would execute the [else statement](https://github.com/BeamMP/BeamMP/blob/development/lua/ge/extensions/MPVehicleGE.lua#L927) (as the jbm changed) and run `spawn.setVehicleObject()` which may or may not can just change the color if nothing else is within the edit packet and i believe to remember that color edit packets only contain the color change, but [the code](https://github.com/BeamMP/BeamMP/blob/development/lua/ge/extensions/MPVehicleGE.lua#L784) doesnt reflect that. I have to run tests~~

**Comment by OfficialLambdax** [comment]
Ok i can reproduce it
![kjkhjkjkhjkhj](https://github.com/BeamMP/BeamMP/assets/91626975/066b5c45-f120-4915-a548-567f4884f7d0)

When the Json within the Edit packet (Oc) does not contain the "paint" value which is within "vcf" then it will not update the colors.. but just update the jbm and parts. This way keeping the colors the same. This may happen when the .pc file the user loads does not contain color values. I am not sure

1. Spawn vehicle
```json
Os:0:{"pos":[-173.73863220215,109.95217132568,92.074157714844],"rot":[0,0,0.99756389856339,0.06975769251585],"pid":0,"vid":15859,"vcf":{"mainPartName":"bluebuck","vars":{},"partConfigFilename":"vehicles/bluebuck/taxi.pc","parts":{"bluebuck_driveshaft":"bluebuck_driveshaft","bluebuck_engine":"bluebuck_engine_i6","hubcap_F_14_alt":"hubcap_05a_14_F","bluebuck_intake_i6":"bluebuck_intake_i6","bluebuck_exhaust_i6":"bluebuck_exhaust_i6","bluebuck_fascia_F":"bluebuck_fascia_F","bluebuck_converter":"bluebuck_converter_hi","bluebuck_fender_FL":"bluebuck_fender_FL","bluebuck_fender_FR":"bluebuck_fender_FR","bluebuck_finaldrive_R":"bluebuck_finaldrive_R_355","tire_F_14x6":"tire_F_735_14","tire_R_14x6":"tire_R_735_14","bluebuck_fueltank":"bluebuck_fueltank","bluebuck_gauges":"bluebuck_gauges","bluebuck_engine_i6_internals":"bluebuck_engine_i6_internals","bluebuck_glass_F":"bluebuck_glass_F","bluebuck_glass_R":"bluebuck_glass_R","bluebuck_header_i6":"bluebuck_exhmanifold_i6_stock","bluebuck_door_FL_4door_sedan":"bluebuck_door_FL_4door_sedan","bluebuck_door_FR_4door_sedan":"bluebuck_door_FR_4door_sedan","bluebuck_door_RL_4door_sedan":"bluebuck_door_RL_4door_sedan","bluebuck_door_RR_4door_sedan":"bluebuck_door_RR_4door_sedan","bluebuck_headlight_R":"bluebuck_headlight_R","bluebuck_doorpanel_FR_4door":"bluebuck_doorpanel_FR_4door","bluebuck_hood":"bluebuck_hood","bluebuck_doorpanel_RR_4door_sedan":"bluebuck_doorpanel_RR_4door_sedan","bluebuck_hydraulics":"","bluebuck_innerfender_FL":"bluebuck_innerfender_FL","bluebuck_innerfender_FR":"bluebuck_innerfender_FR","bluebuck_glass_FR_4door_sedan":"bluebuck_glass_FR_4door_sedan","bluebuck_glass_RL_4door_sedan":"bluebuck_glass_RL_4door_sedan","bluebuck_lettering_fascia_F":"bluebuck_lettering_fascia_F_base","bluebuck_sidetrim_4door":"","bluebuck_lettering_fascia_R":"bluebuck_lettering_fascia_R","bluebuck_lettering_fenders_F":"","bluebuck_licenseplate_R":"bluebuck_licenseplate_R","bluebuck_links_R":"bluebuck_links_R_3link_panhard","bluebuck_mirror_L":"bluebuck_mirror_L","bluebuck_mirror_R":"","bluebuck_radiator":"bluebuck_radiator","bluebuck_radsupport":"bluebuck_radsupport","bluebuck_rollcage":"","bluebuck_roofacc":"bluebuck_taxi_sign","bluebuck_seats_F":"bluebuck_seats_F","bluebuck_seats_R":"bluebuck_seats_R","bluebuck_shiftlight":"","bluebuck_shock_F":"bluebuck_shock_F_heavy","bluebuck_shock_R":"bluebuck_shock_R_heavy","bluebuck_spring_F":"bluebuck_spring_F","bluebuck_spring_R":"bluebuck_spring_R","bluebuck_steer":"bluebuck_steer","bluebuck_steering":"bluebuck_steering","skin_interior":"bluebuck_skin_interior_tertiarycolor","brakepad_R":"brakepad_R_premium","bluebuck_suspension_F":"bluebuck_suspension_F","bluebuck_suspension_R":"bluebuck_suspension_R","bluebuck_swaybar_F":"bluebuck_swaybar_F_heavy","soundscape_horn":"soundscape_horn_12","bluebuck_towhitch":"","bluebuck_transmission":"bluebuck_transmission_3A","bluebuck_trunk":"bluebuck_trunk","wheel_F_5":"steelwheel_15a_14x6_F","bluebuck_wheeldata_R":"bluebuck_wheeldata_R","wheel_R_5":"steelwheel_15a_14x6_R","bluebuck_glass_RR_4door_sedan":"bluebuck_glass_RR_4door_sedan","bluebuck_headlight_L":"bluebuck_headlight_L","bluebuck_doorpanel_RL_4door_sedan":"bluebuck_doorpanel_RL_4door_sedan","bluebuck_bumperguards_R":"bluebuck_bumperguards_R","hubcap_R_14_alt":"hubcap_05a_14_R","bluebuck_brake_R":"bluebuck_brake_R","bluebuck_bumperguards_F":"bluebuck_bumperguards_F","paint_design":"bluebuck_skin_taxi","bluebuck_wheeldata_F":"bluebuck_wheeldata_F","licenseplate_design_2_1":"","linelock":"","n2o_system":"","bluebuck_doorpanel_FL_4door":"bluebuck_doorpanel_FL_4door","bluebuck_swaybar_R":"bluebuck_swaybar_R_heavy","bluebuck_frame":"bluebuck_frame","bluebuck_badge_hood":"","bluebuck_badges_body":"","bluebuck_body":"bluebuck_body_4door_sedan","bluebuck_steeringbox":"bluebuck_steeringbox","bluebuck_brake_F":"bluebuck_brake_F","bluebuck_engine_i6_ecu":"","bluebuck_licenseplate_F":"bluebuck_licenseplate_F","bluebuck_glass_FL_4door_sedan":"bluebuck_glass_FL_4door_sedan","bluebuck_bumper_F":"bluebuck_bumper_F","bluebuck_bumper_R":"bluebuck_bumper_R","bluebuck_centerconsole":"","bluebuck_fascia_R":"bluebuck_fascia_R","bluebuck_columnshifter":"bluebuck_columnshifter_A","brakepad_F":"brakepad_F_premium","bluebuck_differential_R":"bluebuck_differential_R_open"},"paints":[{"baseColor":[0.18,0.36,0.09,1.2],"metallic":0,"roughness":1,"clearcoat":1,"clearcoatRoughness":0.09},{"baseColor":[0.89,0.67,0.22,1.2],"metallic":0,"roughness":1,"clearcoat":1,"clearcoatRoughness":0.09},{"baseColor":[0.81,0.64,0.48,1.2],"metallic":0,"roughness":1,"clearcoat":1,"clearcoatRoughness":0.09}]},"jbm":"bluebuck"}
```
2. Send edit without a color value
```json
Oc:0-0:{"pid":1,"jbm":"miramar","vcf":{"mainPartName":"miramar","vars":{},"partConfigFilename":"vehicles/miramar/base_M.pc","parts":{"miramar_bumper_F":"miramar_bumper_F","miramar_bumper_R":"miramar_bumper_R","miramar_differential_R":"miramar_differential_R","miramar_door_FL":"miramar_door_FL","miramar_glass":"miramar_glass","miramar_door_RL":"miramar_door_RL","miramar_door_RR":"miramar_door_RR","miramar_steer":"miramar_steer","miramar_steering":"miramar_steering","miramar_suspension_F":"miramar_suspension_F","miramar_suspension_R":"miramar_suspension_R","miramar_swaybar_F":"miramar_swaybar_F","miramar_engine":"miramar_engine_1.6","miramar_brake_R":"miramar_brake_R","miramar_transmission":"miramar_transmission_4M","miramar_trunk":"miramar_trunk","miramar_exhaust":"miramar_exhaust","miramar_wheeldata_R":"miramar_wheeldata_R","miramar_fascia":"miramar_fascia","miramar_fender_L":"miramar_fender_L","miramar_fender_R":"miramar_fender_R","miramar_spring_R":"miramar_spring_R","miramar_fueltank":"miramar_fueltank","hubcap_F_13":"hubcap_05a_13_F","miramar_headlight_L":"miramar_headlight_L","miramar_headlight_R":"miramar_headlight_R","miramar_hood":"miramar_hood","miramar_mirror_R":"miramar_mirror_R","miramar_mirror_L":"miramar_mirror_L","miramar_licenseplate_F":"miramar_licenseplate_F","miramar_licenseplate_R":"miramar_licenseplate_R","wheel_R_4":"steelwheel_11a_13x5_R","miramar_wheeldata_F":"miramar_wheeldata_F","miramar_lettering":"miramar_lettering","wheel_F_4":"steelwheel_11a_13x5_F","miramar_door_FR":"miramar_door_FR","tire_F_13x5":"tire_F_560_13_thinww","miramar_radsupport":"miramar_radsupport","miramar_taillight":"miramar_taillight","tire_R_13x5":"tire_R_560_13_thinww","hubcap_R_13":"hubcap_05a_13_R","miramar_shock_R":"miramar_shock_R","miramar_brake_F":"miramar_brake_F","miramar_spring_F":"miramar_spring_F","miramar_shock_F":"miramar_shock_F"}}}
```

**Comment by Starystars67** [comment]
This could be related to the issue with beamling colors not syncing correctly too + Color sync issues that are happening on a wider level again.

My work so far shows that the onVehicleSpawned event from the game appears to be called before the colors are set on the vehicle. As such we do not know the real colors of the vehicle that the player chose. This is why when the player clicks sync after spawning the vehicle it corrects.

Presently I have no idea how to ensure we have the real paint data for the vehicle when the game seems to call the event before it is truly update/ready.

A way to ensure that this data is sent is to send the vehicle data as an edit (by calling the function) when you know it is your vehicle. This is obviously not the ideal solution but does prove the issue root cause.

**Comment by OfficialLambdax** [comment]
Not related to this issue no. The paints data being invalid when accessed during the onVehicleSpawned event is a new bug since 0.31

**Comment by WiserTixx** [comment]
If I am not mistaken this should have been fixed.
