### ISSUE TITLE
if GameVersion != SupportedVersion then abort BeamMP load

### ISSUE THREAD

**Issue by OfficialLambdax** [Starystars67/BeamNG-MP#276]
**A simple check on init of the lua mod that compares the game version against the supported game version.**

Whenever a mayor update of BeamNG drops _the mod becomes incompatible and usually breakes in a way where the players have no idea from where the issues are coming from_. By checking the game version the mod could abort his load and therefore save the players from these bugs.

By not doing this, as it is like know, _every BeamNG related place is flooded with support request_. That includes the BeamNG dc, BeamMP dc, reddit, the forum and what not. This puts more stress on these channels then it should be and it annoys lots of people.

_Players all over the place suggest to each other to rather remove the mod_ (**including BeamNG officially**) because of how "often" it breaks and some suggest the usage of KissMP. So the influence of the current situation is bad for BeamMP and this therefore a required Feature

**Comment by snepsnepsnep** [comment]
That's a really good idea. We can attempt to have the mod unload itself.
