### ISSUE TITLE
[Bug] Rapid accelleration causes emergency brakes and destroyed cars

### ISSUE THREAD

**Issue by OfficialLambdax** [Starystars67/BeamNG-MP#285]
First of all this is a game thing and something that the mod just doesnt address, because of it this could be a feature request, but since it causes issues i think its better to flag it as a Bug.

**Describe the bug**
Sorry for poor english, i have troubles describing this bug.

If a player joins a server while there are players on it that are driving fast cars (any car). After the joining player loaded the already present vehicles the mod applies the other vehicles positions, velocities, rotations etc. The problem that arises here comes from the fact that cars spawn without movement. So once the velocity, rotation etc. is applied to the car, and if the velocity or rotation in any given direction is high enough, then that rapidly accellerates the vehicle. The accelleration can easiely be 20g and higher.

This whole issue comes in my perspective down to very High G that get created through the rapid accelleration.
Let me demonstrate what this does to a vehicle. The video shows a scintilla that is reset and then rapidly accellerated. As you can see in the g meter, the forces (if i read correctly) are at 29g. You can visually see that the vehicle gets demolished. It took several car resets to bring the vehicle to a non damaged state as can be seen further into the video.
https://www.youtube.com/watch?v=IfVrWmtgqGE

This exact behaviour happens to every car that is moving fast after the players client was hung (during vehicle spawn/edit/game pause/lag etc.). If the car has a emergency stopping system (ETK-K, Bastion, Vivace, Scintilla...) then the game also often enables that on the affected vehicles and does not stop until the affected vehicle got reset or stopped. This is why we can see vehicles with fully locked brakes and wheels that are smoking over the asphalt.

**To Reproduce**
1. Join a server where there are players that are driving fast cars. Problem is most prominent on low com vehicles like the scintilla.
2. (Alternative) Message me. I can reproduce the bug with the Bot. All it needs is a simple command in the chat and it replicates it instantly as often as you want.

**Comment by OfficialLambdax** [comment]
A better video
https://www.youtube.com/watch?v=YNcbDDI5EBg

In the 1st. Try you can see visual damages to the car
In the 2nd. you can see that the rapid acc worked mostly nicely
In the 3rd. you can see that the vehicles enabled emergency brakes
In the 4h. you can also see emergeny brakes and that the radiator got damaged (the car starts smoking)
In the 5th. ive reseted the car multiple times by hand, but to no avail, because a reset resets the vehicles velocity and rotation to zero and since its rapidly accellerated again, the same issue breaks it again

**Comment by OfficialLambdax** [comment]
A possible and yet simple way of fixing this issue, without looking to deep into the game to prevent the cars from taking damage for a period of time, is to change the Queing system.

It could still work like now where the spawns/edits are not performed until the player stands still for a period of time, but into equation could put another if statement that only performs the spawn/edit if the quoed vehicle is standing too. So that it stays in quo until that is the case or until the player manually quos by pressing the orange button.

Additionally what could also be done, while at it, is to change the Playername color to Orange while there is a update quoed to it. As this information is otherwise not visible to the players

**Comment by OfficialLambdax** [comment]
With the 0.28 Update this issues has become much more apparent. As now moving vehicles often Spawn with Open doors duo to the extrem g forces.

I heared of a beamng own tool that exists in the world editor that can spawn vehicles no problem at a high rate of speed. Still need to find it and give it a look

**Comment by Starystars67** [comment]
> With the 0.28 Update this issues has become much more apparent. As now moving vehicles often Spawn with Open doors duo to the extrem g forces.
> 
> I heared of a beamng own tool that exists in the world editor that can spawn vehicles no problem at a high rate of speed. Still need to find it and give it a look

Very interesting, please do look into that and share any further information you have around this "tool" as maybe as a group we can research this?

**Comment by WiserTixx** [comment]
This seems to have been fixed. Please reopen if it still happens.
