### ISSUE TITLE
[Feature Request] Highlight player nametags who have a queued event

### ISSUE THREAD

**Issue by Mack29446** [Starystars67/BeamNG-MP#289]
**Is your feature request related to a problem? Please describe.**
Highlight, in some way, players who currently have a queued event.

**Describe the solution you'd like**
Maybe add a * to the user's nametag? (suggestion by @StanleyDudek) this should be discussed

**Additional context**
https://discord.com/channels/601558901657305098/777957916677242939/1054830270391533660

**Comment by OfficialLambdax** [comment]
Also referenced in https://github.com/BeamMP/BeamMP/issues/285
"Additionally what could also be done, while at it, is to change the Playername color to Orange while there is a update quoed to it. As this information is otherwise not visible to the players"

**Comment by OfficialLambdax** [comment]
Will try to think about this when i redo the nametag drawer
