### ISSUE TITLE
[Bug] You have a unpacked version of [ multiplayerbeammp ]

### ISSUE THREAD

**Issue by Starystars67** [Starystars67/BeamNG-MP#293]
**Describe the bug**
The user is presented with an error about the mod being unpacked:

`|E|GELua.core_modmanager.| You have a unpacked version of [ multiplayerbeammp ]. Need to be Packed before update`

**To Reproduce**
1. Start BeamMP and play.

**Expected behavior**
There would be no warning or error presented to the user.

**Screenshots**

**Additional context**

**Comment by Mack29446** [comment]
Duplicate of #287
