### ISSUE TITLE
[Bug] The game is not connected to the launcher issue

### ISSUE THREAD

**Issue by Desoroxxx** [Starystars67/BeamNG-MP#294]
**Have you read our FAQ/Wiki/#before-you-ask ?**
Yes

**Describe the bug**
When making a **clean** BeamMP install, if you go into the multiplayer menu, you will see this:
![image](https://user-images.githubusercontent.com/82710983/210157150-f07d61f7-b780-4551-b7b6-e81859f48c35.png)
This makes the game unplayable (Unless using the workaround at the bottom)

**To Reproduce**
1. Clean uninstall BeamMP, either remove manually left-over folders or use Revo Uninstaller
2. Install BeamMP client from the website
3. Launch BeamMP
4. Go to multiplayer

**Expected behavior**
When you should normally see the window telling you about ToS and Eula that you need to accept, after you accept them you get a prompt to connect your BeamMP account.

**Screenshots**
![image](https://user-images.githubusercontent.com/82710983/210157184-c071506a-e5e6-40c8-a536-12cebafcc408.png)

**Desktop (please complete the following information):**
 - Windows + 11
 - Browser (If applicable): Edge

**Additional context**
There is a workaround to this, when seing the message about "The game is not connected to the launcher!..." you can still see the logout button so here is the workaround:
1. Click logout
Clicking logout will send you to the logging page while bypassing the ToS and Eula.
2. Connect your BeamMP account or click Play as a guest
Wait a bit and you should now see the server page and you are free to connect.

This is the workaround I need to use to play but it as a major problem, you need to redo this each time you Lua reloads (Game launch or when quitting a server).

**Comment by O1LER** [comment]
Same as this:
https://github.com/BeamMP/BeamMP-Launcher/issues/55

**Comment by OfficialLambdax** [comment]
duplicate
