### ISSUE TITLE
Lua is not an acronym, change the About section of the repository.

### ISSUE THREAD

**Issue by ghost** [Starystars67/BeamNG-MP#298]
It appears that the About section of this repository uses LUA rather than Lua, this is incorrect because Lua is not an acronym and should be defined as Lua, which means moon.

**Comment by ghost** [comment]
I'd also suggest disabling the packages section of this repository, as it is unused.
You should also disable Actions & Projects.

**Comment by lionkor** [comment]
> I'd also suggest disabling the packages section of this repository, as it is unused. You should also disable Actions & Projects.

Not really relevant to the project.

> It appears that the About section of this repository uses LUA rather than Lua, this is incorrect because Lua is not an acronym and should be defined as Lua, which means moon.

Feel free to open a PR.

**Comment by lionkor** [comment]
Actually, nevermind, you can't open a PR for that.

Then @Starystars67 you're the only one with access like this, so you can decide if you wanna do this.

**Comment by lionkor** [comment]
The whole "about" section needs an overhaul, it's outdated by like 3 years ;)

**Comment by ghost** [comment]
> Not really relevant to the project.

If you are not using these features, then they are not providing any value to your repository. In general, it is generally a good practice to disable any features that you are not using on your repository. However, if there are any upcoming reasons to leave them enabled, then there is no need to do it.

**Comment by Starystars67** [comment]
Hello, Just thought I would update this.

I have taken your points and made some adjustments to the repository. Thank you!
Please let me know if you find the edits more appropriate or find any other details that would be recommended. :)

Otherwise, Lets move to close this issue.
