### ISSUE TITLE
[Bug] Placeholder orbs are hidden with nametag hiding option

### ISSUE THREAD

**Issue by O1LER** [Starystars67/BeamNG-MP#303]
**Have you read our FAQ/Wiki/#before-you-ask ?**
Yes

**Describe the bug**
Hiding nametags also hides placeholder orbs

**To Reproduce**
1. Connect to a random server
2. Dont load events
3. Hide player nametags
4. Observe that also placeholder orbs vanish

**Expected behavior**
Placeholder orbs should be always visible, since they not only show a players position but also that there is an event to be loaded (or other things depending in orb color). Nametags and orbs should either have their own visibility setting, or orbs should be always visible independent from nametags.

**Screenshots**
The video was made to show an issue with nametag fade out, but at the beginning you can see that the hide nametag option also hides the orb, at the time i wasnt aware that this itself might also be an issue

https://youtu.be/zSVY13sxxBA

**Comment by OfficialLambdax** [comment]
Yeah if we move the blob drawer
https://github.com/BeamMP/BeamMP/blob/development/lua/ge/extensions/MPVehicleGE.lua#L1517
out of this
https://github.com/BeamMP/BeamMP/blob/development/lua/ge/extensions/MPVehicleGE.lua#L1475
this should do the trick.

I think im going to adress this

**Comment by Starystars67** [comment]
> Yeah if we move the blob drawer https://github.com/BeamMP/BeamMP/blob/development/lua/ge/extensions/MPVehicleGE.lua#L1517 out of this https://github.com/BeamMP/BeamMP/blob/development/lua/ge/extensions/MPVehicleGE.lua#L1475 this should do the trick.
> 
> I think im going to adress this

Looks good to me, Do you mind going ahead and raising a PR for it?
