### ISSUE TITLE
[Feature] Way to restore deleted vehicles

### ISSUE THREAD

**Issue by jacobcargen** [Starystars67/BeamNG-MP#304]
As much as I love the ability to remove people that are trolling or are AFK, etc. I think there could be some improvements. Here is an example of what I find it quite annoying. If I remove someone because they are AFK and they begin playing right after, there is only one solution I have to fix this. I have to leave the server and come back. I know that the other player can fix it, but I would rather have a solution for undoing the removal I did. 

Now if it were a simple solution, it would be to add a UI button to add them back while tabbed onto them.

I would like for a way to toggle people on and off. I think that adding a toggle-able option to the player list UI would act as a great solution.

**Comment by jacobcargen** [comment]
I can actually try and attempt this myself.

**Comment by 20dka** [comment]
all you need to do is save the current config in a field inside the vehicle object (MPVehicleGE) and respawn it using that data. the more difficult part (for me) would be making the UI for it
good luck!

**Comment by jacobcargen** [comment]
Okay, thank you for the advice. I will let you know if I fail. Quick question though, what is the easiest way to test? Seems like something that would be hard to test without another player.
How do you test code. Do you go into single player or create a private server or something else?

**Comment by 20dka** [comment]
Yeah I'm not sure you can test this without another person, but at least the other party doesn't need a modified client

**Comment by OfficialLambdax** [comment]
@jacobcargen lemme know your dc name if you want to attempt this yourself. I can give your the ip:port of a private server and connect a bot to it that will have a car spawned for you.

**Comment by jacobcargen** [comment]
@OfficialLambdax Here you go. 

intel i3-530#8485

**Comment by jacobcargen** [comment]
@20dka @OfficialLambdax 
Unfortunately I have been extremely busy and have not made the time to work on this much. If anyone else would like to take this over go right ahead, I didn't make too much progress anyway.

**Comment by Josee-xav** [comment]
Ive actually implemented this myself which allows the user to restore deleted a specificed player vehicle as i do not have an i9 processor or something to process all car physics.

Ill fork this project and upload my changes for anyone that needs it soon just gotta fix some things first

From a quick glance of pull request that supposely closes this issue, it seems like it doesnt have the restore feature? correct me if im wrong.

**Comment by OfficialLambdax** [comment]
Doesnt seem so no, but it looks like that it is intended to be solved with the ui revamp

**Comment by Josee-xav** [comment]
Okay ive uploaded it and seems to fully work from my testing.

To restore a deleted player vehicle you just gotta press the ID of the player in the playerlist and boom itll either queue it or straight away spawn it.  

https://github.com/clodiop/BeamMP

If its fine i can send a pull request
