### ISSUE TITLE
[Bug] Certain serverlist filters can cause the list to stay empty

### ISSUE THREAD

**Issue by O1LER** [Starystars67/BeamNG-MP#308]
**Describe the bug**
When selecting both "Empty only" and "Not empty" serverlist filters at the same time, it will filter out all of the servers, causing the list to be empty

**To Reproduce**
- Go to the serverlist
- Wait for servers to appear in the list
- Activate "Empty only" filter
- Notice certain server to disappear
- Activate "Not empty" filter
- Notice all the servers to disappear from the list

**Expected behavior**
It should not be possible to activate filter combinations that exclude all servers.
If one of the two options is active, the other should be greyed-out.

**Screenshots**
![image](https://user-images.githubusercontent.com/44237025/219970815-a175e1c2-91b8-4fc6-924a-e29754317050.png)
![image](https://user-images.githubusercontent.com/44237025/219970822-a9873d49-9ec0-4937-abba-92a4103510f8.png)
![image](https://user-images.githubusercontent.com/44237025/219970855-45730edb-492c-41b5-a032-8849c50f324a.png)

**Comment by Starystars67** [comment]
This should be resolved now by the addition of this commit: https://github.com/BeamMP/BeamMP/commit/09ffa92af14dd4fd63a6131e0c59284b06bb6f15.

I will close this for now however if you are experiencing it still please open this issue again.
