### ISSUE TITLE
Polish translation 

### ISSUE THREAD

**Issue by JamesBlad** [Starystars67/BeamNG-MP#310]
Hi I have a question. I noticed that the Polish language is missing in the BeamMp interface. I can do a Polish translation if you want, it would make things a lot easier for young players

I think in future you could add more languages.
Please reply. 
Regards JamesBłąd

**Comment by Starystars67** [comment]
Hello James,

We are most definitely open to including additional translations of BeamMP!

If you are happy to do the translations then please open a PR on this repository and we will gladly review and merge accordingly.

If you require assistance with how to create the translations for the mod then please also let us know and we can assist you.

Kind regards,
Titch

**Comment by JamesBlad** [comment]
Hi. I think I can start next week. My question is do i get a template, which I could translate. I prefer contact on discord JamesBłąd#2388. 

Kind Regards _JamesBłąd_

**Comment by Starystars67** [comment]
Hi,

Regarding a template, the English one is located here: https://github.com/BeamMP/BeamMP/blob/development/mp_locales/en-US.json. If you clone the repository, create a `pl-PL.json` file along side the other translations and then when you are done raise a PR from your fork. 

On a separate note, I have messaged you on discord to facilitate helping you if you require any further assistance. 

Thanks

**Comment by Starystars67** [comment]
Further discussion is being had on Discord.

**Comment by Starystars67** [comment]
Closing this issue as it has now been resolved with PR:
https://github.com/BeamMP/BeamMP/pull/330
