### ISSUE TITLE
[Bug]Comments on SendErrorsShowMessage and SendErrors in the ServerConfig.toml seem to be mixed up

### ISSUE THREAD

**Issue by SteliosLL** [Starystars67/BeamNG-MP#312]
![εικόνα](https://user-images.githubusercontent.com/55713334/225113292-eb5c01e9-4d90-42bd-abea-06cedd0458bb.png)
It looks like the 2 comments as seen in the image above, need to be swapped places, because otherwise it doesn't make sense.

**Comment by Starystars67** [comment]
Hi there,

This issue should be on the [BeamMP-Server](https://github.com/BeamMP/BeamMP-Server) repository.

I will recreate this issue over there now and close this one.

Thank you
