### ISSUE TITLE
[Bug] Remove newFeatures module

### ISSUE THREAD

**Issue by OfficialLambdax** [Starystars67/BeamNG-MP#315]
**Have you read our FAQ/Wiki/#before-you-ask ?**
No

**Describe the module**
BeamMP\ui\modules\newFeatures contains 2.3MB of useless data, that is not used.
The entire mod has a size of 4.15MB. 2.3MB of those are literally just used for a gif within that folder.

**Comment by Starystars67** [comment]
Hey! 

You know what, that it a great point!

I will raise a PR to remove that now.
