### ISSUE TITLE
Heavily unoptimized, mod should be reconsidered.

### ISSUE THREAD

**Issue by ghost** [Starystars67/BeamNG-MP#317]
There should be more prerequisites and features to prevent compatibility issues with this mod.

- [ ] The mod accounts for players with memory or threading capabilities. This will ensure that when a player joins a server they will be asked whether to load the vehicles of any players. This feature would greatly improve performance and to allow the user to hand-select the users they want to see the vehicles of is a critical decision that should be made.
- [ ] The mod uses the best Lua practices and formatting to ensure the safety and integrity of code execution. When the player uses this mod they should be garunteed the full service of the mod. I believe the mod does not meet this criteria because the code is not using the most up-to-date practices, is heavily unoptimized with incorrect usage of keywords. The Lua VM has full debug library access and this should not be allowed in such a mod. You should be limiting the amount of developer input unless using a development-based branch of BeamMP (not to be confused with the main branch "development") that supports developer features.

I could go on and on about how BeamMP, and even the game, BeamNG.drive, are both very heavily unoptimized. Who am I to talk, though? Well the point is that I've been working with Lua for roughly seven years. That is more experience than any other language I have known and I definitely make my own mistakes but I do know my practices.

I could give you hundreds of fixes that should take effect immedaitely though unfortunately the development progress of this mod is slowed by the sheer inefficiency and incompetence of the developers along with the instability of the software.

**Comment by ghost** [comment]
New issues have been created to address these problems: #320 #319 #318

**Comment by lionkor** [comment]
> incompetence of the developers

I dont think we've interacted before? I agree some of BeamMP needs fixes and reworking, but you can't make statements like that and not expect a little bit of push back. I dont even write Lua, I dont know what this is about, I just feel the attack maybe a bit hot headed.

**Comment by lionkor** [comment]
Mention people by name if you have criticism, leave other out of it.

I agree with everything else you said, fully.

**Comment by ghost** [comment]
I'll close this one for the rest of the issues so that those can be considered instead.
