### ISSUE TITLE
Implement entity prioritization to improve network performance.

### ISSUE THREAD

**Issue by ghost** [Starystars67/BeamNG-MP#319]
Entity prioritization works better than sending and receiving data for all entities in the game world at the same rate because it reduces the amount of data that needs to be sent and received between the server and clients. By prioritizing important entities such as the player's own vehicle and nearby vehicles, the game can send and receive their data more frequently, providing a more accurate and up-to-date representation of those entities to all clients.

This reduces the amount of network traffic and data that needs to be processed by each client, resulting in improved network performance, reduced lag, and a smoother multiplayer experience. By sending and receiving data more frequently for important entities, players will have a more accurate and responsive experience, improving the overall gameplay experience.

- [ ] **Identify important entities** – We need to identify which entities are important and should be prioritized. This could include the player's own vehicle, nearby vehicles, and entities that are currently being interacted with.
- [ ] **Implement prioritization logic** — We should implement logic that prioritizes important entities and sends and receives their data more frequently than less important entities. This could involve dividing the game world into smaller areas and only sending and receiving data for entities within each area or implementing a system that dynamically adjusts the data rate for each entity based on its importance.
- [ ] **Test and refine** — After implementing entity prioritization, we should test and refine the system to ensure that it is improving network performance and reducing lag.

**Comment by OfficialLambdax** [comment]
chatgpt doesnt understand beamng multiplayer complexity and how vehicle prio would negatively affect gameplay
