### ISSUE TITLE
Implement interpolation to reduce network traffic and improve network performance.

### ISSUE THREAD

**Issue by ghost** [Starystars67/BeamNG-MP#320]
In interpolation, the client calculates the movement of the entity between the last update received and the next update that is received from the server. Rather than waiting for every single update from the server, the client can interpolate the movement and position of the entity between the last and next update. This can reduce the amount of data that needs to be sent and received between the server and clients, improving network performance and reducing lag.

Interpolation can use different techniques to smooth out movement, such as linear interpolation, which uses a straight line to interpolate between the last and next updates, or more advanced techniques such as cubic interpolation or Bezier curves, which can provide a smoother and more natural movement.

- [ ] **Identify entities for interpolation** — We need to identify which entities are suitable for interpolation. Typically, entities that move smoothly and predictably, such as vehicles or other objects with physics-based movement, are good candidates for interpolation.

- [ ] **Implement interpolation logic** — We should implement logic that smoothly interpolates between updates, rather than sending every single update. This could involve using linear interpolation or more advanced interpolation techniques, such as cubic interpolation or Bezier curves.

- [ ] **Test and refine** — After implementing interpolation, we should test and refine the system to ensure that it is improving network performance and reducing lag. We should also ensure that it is not introducing any new issues or problems, such as visual artifacts or incorrect positioning.

**Comment by lionkor** [comment]
We already do this.

**Comment by ghost** [comment]
> We already do this.

Are you sure?

![image](https://user-images.githubusercontent.com/115854106/228633807-883b1e82-f6c2-4440-870b-c624893faaa0.png)

**Comment by ghost** [comment]
Yes, I understand this is the client, but that's the whole point. The client should be making these changes, while the server should be maintaining a stable flow of packets. I don't know why we're sticking to a method that has been used for ages. It may work in the short run but it causes signifigant performance drops in larger servers.

**Comment by lionkor** [comment]
> > We already do this.
> 
> Are you sure?
> 
> ![image](https://user-images.githubusercontent.com/115854106/228633807-883b1e82-f6c2-4440-870b-c624893faaa0.png)

Yes. I'm sure, still.

**Comment by lionkor** [comment]
We do this in the client Lua

**Comment by ghost** [comment]
Barely. I don't really see the necessity of such network requests if this is the case. Also, if you've got a problem with me, just say it? Don't waste my time, so I don't waste yours.

If naming out incompetence goes out to anyone, it's you, because you've asked. If you find it so offensive that I am not naming off any single person then I could admit that it's the entire organization. You are all nothing but hunched back, thinking that what you all have created is something that is in the masses and is at the top of it's game. I'll move to my own work, and sure you'll laugh about it, but it's an honest and more open-ended resolution that I am willing to take.

You either genuinely believe that you know what you're doing, you don't want to admit you are making mistakes, you are saving a face, or avoiding conflict. Either way you've done all the contradictory, proving to me your arrogance.

**Comment by lionkor** [comment]
don't care, someone else deal with this shit

**Comment by Starystars67** [comment]
Hello @shawnjb ,

Position prediction is something that we already conduct here in the lua side of the project. 
Please see [velocityVE.lua](https://github.com/BeamMP/BeamMP/blob/development/lua/vehicle/extensions/BeamMP/velocityVE.lua) as this is where we do use a system to smooth movements out. We use applied force to continue velocity of the object to keep it smoother. Interpolation is used to predict the general direction the object is heading and the continuous position data helps to keep it as accurate as possible.
