### ISSUE TITLE
Add a workaround method to force multiplayer menu to show up, if another update like 0.28 breaks the menu

### ISSUE THREAD

**Issue by finicu212** [Starystars67/BeamNG-MP#327]
**Is your feature request related to a problem? Please describe.**
On 0.28 the multiplayer menu was broken. 

**Describe the solution you'd like**
It'd be nice to have a workaround to force the multiplayer menu to show up via a key combination or some console command, while people wait for a fix

**Comment by O1LER** [comment]
The menu wont help much if the rest of the multiplayer is broken due to the game update

**Comment by Starystars67** [comment]
Hey, thank you for opening this issue.

We used to have BeamMP run automatically without checking the game version, however, this created issues where there were incompatibilities with the game so we had to introduce this version checking.

I hope you can understand our reasoning and if you have any suggestions on how we could approach it differently please do let us know.

Kind regards,
