### ISSUE TITLE
BeamMP breaks highlighting and hiding parts [Bug]

### ISSUE THREAD

**Issue by 2PXL** [Starystars67/BeamNG-MP#338]
since BeamMP is missing the "Highlight Subparts" option in the vehicle editor, it won't allow highlighting and hiding parts.

Vanilla: https://imgur.com/WheYEzG

BeamMP: https://imgur.com/XCJAHcA

**Comment by Please-Pick-a-Name** [comment]
i tried to deal with it in #348
no idea if its bug free?
