### ISSUE TITLE
[Bug] Serverlist has missing country flags

### ISSUE THREAD

**Issue by O1LER** [Starystars67/BeamNG-MP#346]
The following country flags are missing as far as i know:

- South Africa
- Taiwan
- Thailand
- New Zealand
- Lithuania
- Iceland
- Hong Kong
- Greece
- Finland
- Belarus
- Azerbaijan

There might be more, but those were servers that were online at the time that had no flag to them

**Comment by Starystars67** [comment]
Hey O1LER, Thank you for raising. 

Interesting I was not aware of this so thank you for raising this.
I will look to add a PR to fix this in the near future.

~ Titch

**Comment by Starystars67** [comment]
PR #351 now fixes this issue.
Just awaiting approval. Thanks again @O1LER !
