### ISSUE TITLE
Move 'Quit' button in session UI app

### ISSUE THREAD

**Issue by EventHorizon511** [Starystars67/BeamNG-MP#349]
**Is your feature request related to a problem? Please describe.**
Inadvertently quitting a server is very frustrating. Unfortunately, the placement of the 'Quit' button in the in-game session UI app - especially when manually queueing events - can easily lead to misclicks to exactly this effect.
This is because the 'Quit' button is right next to the 'Events queued' button, so a slight misclick instantly quits the server without additional confirmation. Even worse is the situation where the queued event(s) disappear the second you click the 'Events queued' button, which removes the button and moves the 'Quit' button to the left, potentially clicking quit instead.

**Describe the solution you'd like**
I propose to move the 'Quit' button to the very left of the UI element. This way it's far away from any other button in the session UI and also right next to the server name, which seems logical.
The required code change is trivial.

**Describe alternatives you've considered**
Asking for an additional confirmation before quitting a server would also eliminate this problem. However, it may feel cumbersome for some if the need for a confirmation can not be toggled off in the settings, which in turn makes this solution more complex to implement than the proposed fix.

**Additional context**
Visualization of the proposed change:
![move_quit_button_illustration](https://github.com/BeamMP/BeamMP/assets/39645121/5dc8a408-287c-4738-856b-fc5aa3494e12)

**Comment by x0xDJSx0x** [comment]
I can totally see this, have had a couple times trying to queue a vehicle and just quiting the server.
