### ISSUE TITLE
Make the option "Automatic queue system" more visible - by Razor

### ISSUE THREAD

**Issue by OfficialLambdax** [Starystars67/BeamNG-MP#357]
**Is your feature request related to a problem? Please describe.**
A better visualization of disabling the automatic player update queuing in the multiplayer settings. While it is already deactivatable/changable, it can still be confusing for newer players or non-native english speaking people who want to disable the game from automatically applying edits from other people. For example if you are idle and have the automatic player update queuing enabled (which is enabled by default usually) it can cause you to lag and/or slow down the game as it has to continuesly refresh with each edit getting applied automatically every second. Ex.: Another player is editing their vehicle every second and you currently aren't moving which leads the game to reload every moment when another edit gets applied and queued.

**Describe the solution you'd like**
Rename the settings to be more user-friendly and easier to understand for players that want to change the settings or disable certain features like the automatic player update queuing and applying.

**Describe alternatives you've considered**
Instead of "Automatic queue system", rename it to be something such as "Enable automatic queuing and updating for other player edits" and instead of "Queue player updates" make it be something such as "Enable automatic player update/edit queuing". These are raw ideas, but anything that would be more user-friendly amongst newer players or people who are not native english speakers so it would be easier for them to understand.

**Comment by Starystars67** [comment]
Hello, thank you for raising this.

The following changes have been made in the attached branch. Please let me know your thoughts:

"Automatic queue system" is now "Automatically apply queued vehicle changes"
"Queue player updates": "Enable player vehicle update/edit queuing"

In-Game:
<img width="402" alt="image" src="https://github.com/BeamMP/BeamMP/assets/15389482/89a8537b-5573-4e56-98ec-359ca7452ce9">


~ Titch
