### ISSUE TITLE
Show Vehicle Speed in Nametag as an option

### ISSUE THREAD

**Issue by Mack29446** [Starystars67/BeamNG-MP#364]
As suggested by Neilogical, it would be useful to have an option to show the vehicle's current speed on the nametag.

**Comment by OfficialLambdax** [comment]
Can be archived with scripts using
https://beammp.github.io/BeamMP/modules/MPVehicleGE.html#setVehicleRole
or
https://beammp.github.io/BeamMP/modules/MPVehicleGE.html#setPlayerNickPrefix
