### ISSUE TITLE
[Bug] Mods Crash game when loading/Activating in a Server 

### ISSUE THREAD

**Issue by Cragj** [Starystars67/BeamNG-MP#366]
**Have you read our FAQ/Wiki/#before-you-ask ?**
Yes/No
Yes

**Describe the bug**
It happens when ever I active mods on a server (CLIENT SIDED)
Or I Load mods before Joining a server
I had 230 Mods But even after i cut it down to 70 ( 70 used to work)
**To Reproduce**
1. Go to 'Mods'
2. Click on 'Repo'
3. Click on 'activate mods'

**Expected behavior**
To be able to use engine mods for drifting.
**Screenshots**
N/A as It just crashes
**Desktop (please complete the following information):**
 - OS + Version: [e.g. Windows, Unix/Linux]
 - Browser (If applicable): [e.g. Chrome, Opera]
Oprea GX - Windows 11 64X
**Additional context**
70 mods used to work fine before i stopped playing the game for a couple of months
But i do have a suspicion it may be my Automation build But i have looked through the FAQ and nobody else has this issue
Also when it crashes it Can either Crash my whole pc and cause a Reboot or Crash the game

**Comment by Cragj** [comment]
I have 16gb of ram also

**Comment by OfficialLambdax** [comment]
You are out of luck with this one. That some can still activate mods while in a server is a bug. You shouldnt be able to. It was a complaint by many players and server admins that players just used foreign mods on their servers.

**Comment by Cragj** [comment]
bruh.

**Comment by OfficialLambdax** [comment]
There have been serious discussions about it in the communities and the mp team, but most say, _no, block mods_. Sry dude

**Comment by Starystars67** [comment]
Use of your own server would permit you to run your choice of mods if you wish to play with your friends.
https://forum.beammp.com/t/tutorial-how-to-setup-beammp-server/69
