### ISSUE TITLE
Unattended installer for Proton?

### ISSUE THREAD

**Issue by Legion495** [Starystars67/BeamNG-MP#372]
**Is your feature request related to a problem? Please describe.**
Well in short the Game is great and there are some efforts to get this working with Proton.
The issue I have is after the selection of the language of the installer proton/wine fails to show the installer correctly.
Further selection is not possible anymore. Like 2 clicks away from being able to use it.

**Describe the solution you'd like**
It would be great if there could be a unattended version.
I know the installer supports silent options but I cannot trigger them on a proton install it seems.

**Describe alternatives you've considered**
I have tried many methods and the last solution I have is streaming the MP version of the game but it is far from being perfect.

**Comment by Starystars67** [comment]
@Anonymous-275 this is one for you I think.

**Comment by Legion495** [comment]
Yes and no.
There is in fact a old guide on reddit but I assume it is not working correctly on wayland.

Which is what got me here.
Preferably would a SKSE Solution which swaps out the exe and renames the old one.

Since BeamMP does offer Linuxservers I wanted to see if this is something that is worthy of consideration.

https://www.reddit.com/r/BeamMP/comments/oi67rf/beammp_on_linux_guide/

There are even automated scripts for it.
I tried. And I thought the best and smartest way would be if some install method reliable for Proton could be established.

I fully understand if this will be denied. I wanted to at least ask once.

**Comment by Legion495** [comment]
Sorry closed by accident

**Comment by Starystars67** [comment]
Would it help at all that you can get the launcher and run it from any location you like without using the installer?
You can download it from the github releases: https://github.com/BeamMP/BeamMP-Launcher/releases/tag/v2.0.82

**Comment by Legion495** [comment]
I am kissing you.
So this one I managed to get running with SteamTinkerLaunch(do not forget to select the correct Protonversion in STL):
![image](https://github.com/BeamMP/BeamMP/assets/15214766/7a087801-005d-4c94-9b2c-9446cd7c30db)
I had to reactivate mods on the first launch.
![image](https://github.com/BeamMP/BeamMP/assets/15214766/18393b7e-0a43-40fe-9fbe-9ab166f692ad)

Also if someone wants to run this directly with proton.
It did not work out as I expected but this would be somewhere along the lines of this:

STEAM_COMPAT_CLIENT_INSTALL_PATH="/home/legion495/.local/share/Steam" STEAM_COMPAT_DATA_PATH="/mnt/media/steam/SteamLibrary/steamapps/compatdata/284160/pfx" WINEPREFIX=$PWD "/mnt/media/steam/SteamLibrary/steamapps/common/Proton 8.0/proton" run ./drive_c/users/steamuser/Desktop/launcher.exe


So yes the launcher made it possible for me. I will close this.
Maybe it could be referenced for Linux Proton use.

**Comment by Starystars67** [comment]
Hey @Legion495, Would you mind writing this up as a guide for other users on our [Forum](https://forum.beammp.com)?

That way it can help others for the future.

**Comment by Legion495** [comment]
@Starystars67 

I wish I could post more screens but I think this will be good enough. 
I hope it is tagged to your liking.
https://forum.beammp.com/t/linux-setup-beamng-mp-proton-with-steamtinkerlaunch/688297

**Comment by lionkor** [comment]
It would make make sense to make a Lutris install script, I believe?

**Comment by lionkor** [comment]
Lutris in general lets you select a lot more options regarding game launch, wine prefix, wine version (and it includes GE proton versions) so I'd recommend that.

**Comment by Legion495** [comment]
You are free to do that and add it to the guide.
I would want to avoid to introduce another Launcher Application...
I have no clue how that is done. 
You may also use Proton+/up and so on to download Proton GE and or Steamtinkerlaunch to fetch the latest GE.

The guide is merely based on my abilities and I stopped fumbling around with Lutris for a long time now.

**Comment by Starystars67** [comment]
> @Starystars67
> 
> I wish I could post more screens but I think this will be good enough. I hope it is tagged to your liking. https://forum.beammp.com/t/linux-setup-beamng-mp-proton-with-steamtinkerlaunch/688297

Spot on! Thank you, I have now pinned this for others to fine easily.
