### ISSUE TITLE
[Bug] highlighted parts on custom part, no highlight

### ISSUE THREAD

**Issue by YannD-Deltagon** [Starystars67/BeamNG-MP#382]
**Have you read our FAQ/Wiki/#before-you-ask ?**
Yes

**Describe the bug**
When I launch BeamNG (even without the BeamMP launcher) but the BeamMP.zip mod is present and ACTIVE, in-game, in the "Vehicle Config" tab, it no longer highlights the parts of the car on which I click. If I remove the mod + press F5, then the button appears, and it highlights correctly. It's very inconvenient to lose this on the server.

**To Reproduce**
1. Go to 'Vehicle Config' tab with BeamMP.zip mod active
2. Click on any part of the car
3. Notice that the part is not highlighted
4. Remove the mod + press F5
5. See that the part is now highlighted

**Expected behavior**
I expect the parts of the car to be highlighted when clicked on, even with the BeamMP.zip mod active

**Desktop (please complete the following information):**
 - Windows 11 64bits (Insiders)

**Additional context**
If there's a reason not to fix this, please explain how I can reactivate it on my side
It's too inconvenient to lose this feature on the server

**Comment by OfficialLambdax** [comment]
Already fixed https://github.com/BeamMP/BeamMP/pull/348
will be available to all users on the next update of BeamMP
