### ISSUE TITLE
[Bug] attempt to index a nil value

### ISSUE THREAD

**Issue by AnErrupTion** [Starystars67/BeamNG-MP#393]
**Have you read our FAQ/Wiki/#before-you-ask ?**
Yes

**Describe the bug**
The game freezes shortly after BeamMP tries to get some stuff from BeamNG.drive, I think?

**To Reproduce**
1. Start the BeamMP launcher.
2. Wait for BeamNG.drive to launch.
3. Admire the bug!

**Expected behavior**
I expected the game to not freeze.

**Screenshots**
![image](https://github.com/BeamMP/BeamMP/assets/49339966/f172e29d-490a-4b08-9d0b-2f6c5783018e)

**Desktop (please complete the following information):**
 - OS + Version: [e.g. Windows, Unix/Linux] Void Linux (kernel 6.5.5_1)
 - Browser (If applicable): [e.g. Chrome, Opera]

**Additional context**
None

**Comment by OfficialLambdax** [comment]
What version of the Launcher do you use?

**Comment by AnErrupTion** [comment]
@OfficialLambdax I'm using the v2.1.0 pre-release.

**Comment by OfficialLambdax** [comment]
> @OfficialLambdax I'm using the v2.1.0 pre-release.

2.1 is known to not work with 0.30 atm. You will have to go back to 2.0

**Comment by AnErrupTion** [comment]
@OfficialLambdax Thanks! Seems like it worked! (For some reason the latest 2.0 version didn't work for me last time, the game kept telling me it couldn't connect to the launcher, but now it can... I keep having weird issues with BeamMP on Linux unfortunately :v)
