### ISSUE TITLE
[Feature Request] Featured servers/Categories for servers

### ISSUE THREAD

**Issue by Hellrockets117** [Starystars67/BeamNG-MP#400]
**Is your feature request related to a problem? Please describe.**
I think I am not alone when it comes to BeamMP servers when I say it is hard to find consistent and quality servers or it can be hard to find content. I feel like I have only found decent servers through word of mouth.

**Describe the solution you'd like**
A featured servers list, paid promo, or even just a recommended servers list by the staff

**Describe alternatives you've considered**
If something like this in the UI is difficult to add or just not a good option, maybe a section in the BeamMP discord for servers could be a good alternative.

**Additional context**
A lot of good servers are likely overlooked just simply because they lack the promotion and outreach. A paid promotion section could be a good motivator for the staff team to help raise funds for the development team to add more features and QOL things like this

**Comment by NicholasMcMillan03** [comment]
It would definitely be nice to have server that add either something especially unique or interesting experience with either custom or curated content and good staffing. It can be hard to find a good server that is actually well moderated, has stable mods, and has a consistent experience between sessions.

**Comment by PicklesMcGee** [comment]
I had to search RP to find a server worth playing!

**Comment by BlurryPlaysToo** [comment]
yeah I would love it. With a normal PC and working fulltime it is sometimes very hard to find some servers to play...
Like everytime loading all in, then leaving and searching for the next gets really fast frustating and often ends in just switching the game.
