### ISSUE TITLE
[Bug] imgui chat window initial display state is collapsed

### ISSUE THREAD

**Issue by StanleyDudek** [Starystars67/BeamNG-MP#438]
**Have you read our FAQ/Wiki/#before-you-ask ?**
Yes

**Describe the bug**
After very first enabling of the imgui chat in a clean user folder, it starts in a collapsed, minimal dimensions state, there may be no dimensions declared with `gui.registerWindow()`

**To Reproduce**
1. Clean user folder
2. Launch BeamMP
3. Enable imgui chat
4. Connect to server
5. See collapsed imgui chat in top left

**Expected behavior**
An appropriately sized chat window is presented.

**Screenshots**
![image](https://github.com/BeamMP/BeamMP/assets/49531350/fc9b25c0-5064-4006-92a2-8f6e47da91db)

**Desktop (please complete the following information):**
   - OS + Version: W11, BeamMP 4.9.7 (and prior)

**Additional context**
I'll fix it.

**Comment by Starystars67** [comment]
Hi @StanleyDudek , Thank you for reporting.

Regarding you fixing it, thank you. please be sure to link this issue to the PR you raise.

Thanks again
