### ISSUE TITLE
[Feature Request] Client support for Prevention of Vehicle Config Cloning and Configuration Saving

### ISSUE THREAD

**Issue by StanleyDudek** [Starystars67/BeamNG-MP#451]
**Is your feature request related to a problem? Please describe.**
Some players do not want other players to be able to clone and / or save their vehicle configurations. This is reasonable, and support for it should be possible.

**Describe the solution you'd like**
In BeamMP's Multiplayer Options, a pair of options for:
* Preventing Cloning, and
* Preventing Configuration Saving

If a player has either of these enabled, other players on the server should not be able to perform the corresponding action to that player's vehicle.

**Describe alternatives you've considered**
I've personally created a client mod that can prevent anyone from cloning or saving configurations, but this includes the player themself.

**Additional context**
Making other clients aware that a certain client prevents cloning or saving of the vehicle in question may be tricky, or involve server work to support it. This could potentially be a public resource of a server plugin / client mod pairing, but building this into BeamMP itself would be much more robust.

**Comment by Starystars67** [comment]
Sadly there is no real way to properly prevent this at the moment.
That said if you have a means to at least limit some of it please consider sharing this and we can look into implementation within BeamMP.

The only idea that comes to mind for this would be to build it into each of the UI elements where this is done and try that way OR find how it is done within the games lua and modify it there based on a check within the vehicles details.

Edit:

Maybe a modification of `core_vehicles.cloneCurrent` with a check for if cloning or copying is permitted would work here?
Same for `core_vehicle_partmgmt.saveLocal`.

Maybe we can even do this without needing to make a copy of the file?

**Comment by snepsnepsnep** [comment]
This used to be a feature at some point. I can re-implement it client side but we would need a way for the server to broadcast client settings to other players for it to work.

**Comment by Starystars67** [comment]
I was thinking that the client chose to protect a config when they spawn it, this would be sent as part of the vehicle config and then when spawned it would be applied accordingly.

**Comment by snepsnepsnep** [comment]
Sounds doable. I'll look into it.
