### ISSUE TITLE
Game-Breaking Bug!

### ISSUE THREAD

**Issue by zeruthewolf** [Starystars67/BeamNG-MP#473]
**Have you read our FAQ/Wiki/#before-you-ask ?**
Yes (I have mentioned this on the Discord multiple times, and has gotten no-where)

**Describe the bug**
The Issue that is game-breaking is when I happen to spawn a car, or exit my vehicle (happens to my friend as well), it would sometimes soft-lock the whole game. What I mean by this, every app, and UI will completely freeze. The speedometer does not even function, and almost every hotkey is non-functional. I hit ctrl+e, nothing, ESC, nothing, etc. I checked console, nothing. NOTE: I am running on a complete vanilla NO MODS server I host. I have tried clearing cache, only having multi enabled, and verifying everything, and it still presists. 

**To Reproduce**
I have found the easiest way to reproduce this issue for myself. I just spam f to exit and re-enter my vehicle several times, revving the vehicle to see if the speedometer is still functional, until i spot that the speedometer is frozen, i then have no longer have control of any hotkeys besides a few like world editor and console. cant show the UI, pause game, etc. (NOTE: I know that theres a hide ui hotkey, trust me, its not that, and also tried reloading lua)

**Expected behavior**
Again, exiting and re-entering your vehicle several times, the hotkeys will not function, pause wont work, esc does absolutely nothing, and only way of fixing it is rejoining, and this happens every time, so it's practically impossible to switch cars.

**Screenshots**
N/A - cant really show unless its a video. my setup isnt clean but mark my word, this is really stressful for my friend and i since were having the same issues.

**Desktop (please complete the following information):**
 - Windows 11
 - Browser (idk why beammp would need the browser but windows edge)

**Additional context**
I tried posting this issue on the discord, but the devs there keep telling me to verify this, and to clear cache. I done that all, i have a clean install, and problem still persists. Even the invisible snowman bug is still being mentioned by a lot of people.

**Comment by Starystars67** [comment]
Hello @zeruthewolf , Thank you for reporting and I am sorry that it seems to have not made its way to us on the development side.

Please can you provide your game log file for us to review for any errors that could give us an indication as to where this is happening or what is causing it?

**Comment by Starystars67** [comment]
With regards to the invisible snowmen issue this was only recently introduced and has now been fixed.
