### ISSUE TITLE
Ability to translate Turkish language in GitLocalize

### ISSUE THREAD

**Issue by YumiNee213** [Starystars67/BeamNG-MP#499]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Making Turkish language available in BeamMP's GitLocalize page.

**Describe alternatives you've considered**
The translation can be updated with a pull request like done as in the past.

**Additional context**
I translated the mod to Turkish in the past, but now I was a little confused about whether to make a pull request or use GitLocalize when new strings are added. Unfortunately I could not find the language there. If its okay to make a pull request I can do it that way as well :D

**Comment by Starystars67** [comment]
Hello, My apologies for the delay on this.

I have created a new entry for Turkish on our GitLocalize. You can find it here:
https://gitlocalize.com/repo/9181/tr

Thank you for your interest!
