### ISSUE TITLE
[Bug] TriggerServerEvent does not transmit data from client to server.

### ISSUE THREAD

**Issue by JotaFaD** [Starystars67/BeamNG-MP#500]
**Have you read our FAQ/Wiki/#before-you-ask ?**
Yes

**Describe the bug**
Calling TriggerServerEvent("EventName", "testData") does not transmit "testData" to the server. The data received is always "0". TriggerClientEvent works as expected.

I found a forum post from 2021 that has the same issue, but no solution:
https://forum.beammp.com/t/cant-transmit-data-from-client-to-server/173978

**To Reproduce**
Client Code:
```lua
TriggerServerEvent("BeamRPTriggerHit", "test")
```

Server code:
```lua
function onBeamRPTriggerHit(data)
	print("Trigger hit")
	print(data)
end

MP.RegisterEvent("BeamRPTriggerHit", "onBeamRPTriggerHit")
```

Consoles always returns data equals "0":
![image](https://github.com/BeamMP/BeamMP/assets/3308180/d24b8deb-45c5-41ad-9556-f8295b98119f)

**Expected behavior**
Server callback receives the data passed by the client

**Desktop (please complete the following information):**
 - Windows 10 22H2

**Additional context**
Client and Server running on the same machine, maybe makes a difference?

**Comment by OfficialLambdax** [comment]
try this. the first argument contains the origin, to tell you which client send the data.
```lua
function onBeamRPTriggerHit(playerId, data)
	print("Trigger hit from " .. playerId)
	print(data)
end

MP.RegisterEvent("BeamRPTriggerHit", "onBeamRPTriggerHit")
```

**Comment by JotaFaD** [comment]
It worked. Thanks for the help
