### ISSUE TITLE
playerController.lua is out of date

### ISSUE THREAD

**Issue by OfficialLambdax** [Starystars67/BeamNG-MP#501]
BeamMP ships a copy of the game own [playerController.lua](https://github.com/BeamMP/BeamMP/blob/development/lua/vehicle/controller/playerController.lua), our version is outdated.
- [x] Figure out why BeamMP needs to patch this game file.
- > beammp patches the playercontroller to update electrics of the unicycle. I expect that it is done to sync unicycle related values with other players through the mods electrics sync
- [x] Update the file

**Comment by StanleyDudek** [comment]
This is mainly the code that BeamMP adds: https://github.com/BeamMP/BeamMP/blob/05d5dc237cbd4e91a428078abf95f33e15682657/lua/vehicle/controller/playerController.lua#L304

the rest of the file is outdated when compared to current game-supplied playerController.lua
