### ISSUE TITLE
Persistent serverlist searchfield

### ISSUE THREAD

**Issue by O1LER** [Starystars67/BeamNG-MP#504]
Serverlist searchfield gets cleared when updating the serverlist. If i search for carp, i would like to update just these entrys, not search for them again

**Comment by snepsnepsnep** [comment]
Cannot replicate. Unless you mean something else other than the Refresh button for "updating the serverlist"

**Comment by Starystars67** [comment]
Indeed, cannot replicate.
Closing until further information is provided.
