### ISSUE TITLE
Consistent mod list ordering of BeamMP servers 

### ISSUE THREAD

**Issue by StanleyDudek** [Starystars67/BeamNG-MP#527]
**Is your feature request related to a problem? Please describe.**
Servers hosted on Linux appear to have an arbitrary load order of client mods (i.e., not alphabetical)

Just look at a few mod listings on the server list, any in alphabetical order are hosted on windows, any in an arbitrary order are hosted on Linux.

**Describe the solution you'd like**
No matter what order the server loads client mods and gives the mod list to the back end, have the client parse the mod list into alphabetical order

**Additional context**
Some mods, most often mods of mods, need a specific load order, typically alphabetical would suffice, i.e., modName.zip loads before modNameZZZ.zip

**Comment by Starystars67** [comment]
I think this is more an issue for the BeamMP-Server repo.
@lionkor can you confirm?

**Comment by lionkor** [comment]
I thought so, too, @Starystars67, but dudeks suggestion of having the launcher/game do it is more reliable

**Comment by Starystars67** [comment]
Understood, PR raised to address.
