### ISSUE TITLE
Feature Request: Translucent Name Tags

### ISSUE THREAD

**Issue by Probler-Yt** [Starystars67/BeamNG-MP#574]
Description:
Currently, name tags in the game can be very obstructive, often blocking important elements in the player's view. This can be particularly problematic during races, chases, or any scenario where a clear line of sight is crucial. While there is an option to disable name tags, this is not ideal for all situations, as players still want to see who they are interacting with.

Suggested Improvement:
Implement an option to make name tags translucent or less obstructive. This way, players can still see the name tags without them blocking the view.

Potential Benefits:

Improved player experience by reducing visual clutter.
Reduced frustration and incidents (such as crashes during races) caused by blocked views.
Enhanced gameplay by allowing players to maintain awareness of other players' identities without compromising their ability to see critical game elements.

Community Feedback:
Many players in the community have expressed frustration with the current name tag system. There have been instances where players rage due to the obstructive nature of name tags, leading to crashes and other negative experiences.

Additional Comments:
While disabling name tags is an existing feature, having a more flexible option like translucent name tags would provide a better balance between visibility and information.

**Comment by OfficialLambdax** [comment]
Whats your opinion on the player name tag fading? Does that perhaps do what you are looking for?
![fddfgdfg](https://github.com/BeamMP/BeamMP/assets/91626975/8b592603-907e-4feb-a1de-d301b9a946f3)
