### ISSUE TITLE
[Question] Overwriting main.js in client mod (file already used by BeamMP)

### ISSUE THREAD

**Issue by JotaFaD** [Starystars67/BeamNG-MP#590]
Have you checked the relevant area on our Forum / Discord / Wiki? **Yes**

Describe your question in as much detail as possible below please:

I'm currently writing a mod that requires the `garagemode` UI state found at `ui/entrypoints/main/main.js`. This state is necessary to use the garage mode that exists in the game, but is deactivated by default.

The `main.js` already has the necessary code for the state, but its commented out in the game and in BeamMP's `main.js`:
```lua
.state('garagemode', {
        url: '/garagemode',
        templateUrl: '/ui/modules/garage/garage.html',
        controller: 'GarageController as garageCtrl',
        // menuActionMapEnabled: false,
        uiAppsShown: true,
        uiLayout: 'garage',
        backState: "menu.mainmenu",
        })
```

During my testing in singleplayer, I just had to overwrite this file inside my own mod with the state enabled. However, this does not work as a multiplayer mod, because the `main.js` file is already used by BeamMP to define its own states for the multiplayer screen. (Does the BeamMP.zip mod takes priority over other mods sent by the server?).

Is there any way I can add this state to the file while still being compatible with BeamMP? Any help is appreciated.

**Comment by Starystars67** [comment]
Hello @JotaFaD and sorry for the delayed response.

Firstly yes BeamMP does take priority over the loaded mods from the server.

In relation to what you are trying to do here though, I am unsure why something like this would be served by the server when the garage is a singleplayer only item?

Could you elaborate on the thinking here please?

Thanks

**Comment by JotaFaD** [comment]
Hi @Starystars67 , thanks for the response.

I needed to modify this file so that I could enable the garage UI in multiplayer.

I ended up finding a workaround to this limitation by creating my own UI app and copying some of the garage code to it, bypassing the necessity to modify the file used by beammp.

This issue may be closed then.

**Comment by Starystars67** [comment]
Okay, happy to hear you found another way!
Thanks for updating.
