### ISSUE TITLE
[Bug] CORS error on server list page

### ISSUE THREAD

**Issue by tsndr** [Starystars67/BeamNG-MP#600]
**Describe the bug**
When visiting https://www.beammp.com/servers the server list stays empty. The "Network" tab shows that there's some CORS misconfiguration. (see screenshot)

**To Reproduce**
1. Go to https://www.beammp.com/servers
2. See empty server list
3. Open Chrome DevTools, navigate to "Network" tab
4. Reload
5. See error

**Expected behavior**
The server list is being displayed.

**Screenshots**
<img width="1552" alt="Screenshot 2024-08-14 at 15 55 00" src="https://github.com/user-attachments/assets/409a8885-3a7a-4253-b967-61b8476b837a">

**Desktop (please complete the following information):**
 - OS + Version: macOS Sonoma 14.5
 - Browser: Brave 1.68.128 Chromium: 127.0.6533.73 (Official Build) (arm64) 

**Additional context**
When checking the URL that's being called, I receive valid JSON:
https://backend.beammp.com/servers-info

**Comment by Mack29446** [comment]
Hey, thanks for flagging this, we thought we had fixed this but it still seems to be happening for some users.

I'll close this issue as it's not strictly for Lua, but we'll keep track internally
