### ISSUE TITLE
[FEATURE] MPVehicleGE.sendPendingVehicleEdits()

### ISSUE THREAD

**Issue by Unshown** [Starystars67/BeamNG-MP#661]
**Is your feature request related to a problem? Please describe.**
I am running a gamemode where it is cruitial that every car is queued before the start of the game. In order to stop edits coming in after game start i need to let every player know to send their pending vehicle edits for others to queue.
Currently it is only possible to call MPVehicleGE.sendVehicleEdit() which sends a edit event to all other users every time even if no event for the players vehicle is queued.

**Describe the solution you'd like**
make the already existing function sendPendingVehicleEdits accessable via MPVehicleGE.sendPendingVehicleEdits()

**Additional context**
It would generaly be wise to not have MPVehicleGE.sendVehicleEdit() available from other extensions since this could be a potential threat for eventspamming. I dont see a reason to force send a vehicleEdit event to the server if the vehicle hasnt been edited to begin with.

Hope this makes sense and in theory should be a quick implementation

Here are the code snippets i am refering to:

![image](https://github.com/user-attachments/assets/e343e235-aba2-4932-8431-8c0f8632f014)
![image](https://github.com/user-attachments/assets/9fd722a9-5795-47e1-880b-8385875e7433)
![image](https://github.com/user-attachments/assets/5b1c895b-6252-4466-a5b0-7b1569547d69)

**Comment by Starystars67** [comment]
@20dka please can you review this one since it is mainly your work here :)
