### ISSUE TITLE
[Bug] Stacktrace when saving config

### ISSUE THREAD

**Issue by Unshown** [Starystars67/BeamNG-MP#665]
**Have you read our FAQ/Wiki/#before-you-ask ?**
Yes

**Describe the bug**
Saving a config causes a stacktrace. Saving still works fine but the trace is not meant to be there im sure

**To Reproduce**
Spawn a car
Edit the car
Save as custom config

**Expected behavior**
Config gets saved without a stacktrace

**Screenshots**
![image](https://github.com/user-attachments/assets/1e143554-3c26-455f-bfb6-dc09307d1db2)

**Desktop (please complete the following information):**
 - Windows 11

**Comment by Starystars67** [comment]
Hello, @Unshown,

Please can you tell me which version of BeamMP you are on?

Thanks

**Comment by WiserTixx** [comment]
This should now be resolved, see #668
