### ISSUE TITLE
[Bug] Serverlist sorting doesnt work anymore

### ISSUE THREAD

**Issue by O1LER** [Starystars67/BeamNG-MP#678]
**Have you read our FAQ/Wiki/#before-you-ask ?**
Yes

**Describe the bug**
Serverlist sorting isnt working anymore since 0.34 update. Shows the error

`CEF.MainGEUI#local://local/ui/entrypoints/main/index.html#/menu.multiplayer.servers:1| Uncaught ReferenceError: sortTable is not defined`

**To Reproduce**
1. Go to serverlist
2. Click on any of the column headers
3. Observe the serverlist not getting sorted
4. Open the console in order to see the above mentioned error

**Expected behavior**
Serverlist should be sorted by whatever header you clicked on

**Desktop (please complete the following information):**
 - OS + Version: Win11 and Debian12
 - BeamMP v4.13.9.3 as well as latest development branch

**Additional context**
sortTable is used in servers.partial.html, lines 59-62
The function is in multiplayer.js, lines 1869-1879

**Comment by WiserTixx** [comment]
Fixed in #644
